x-veld:
  code:

    networks:
      - veld_postgres

    config:
      - environemnt_var: "POSTGRES_USER"
        var_type: "str"
        default: "postgres_user"
        optional: true
      - environemnt_var: "POSTGRES_PASSWORD"
        var_type: "str"
        default: "postgres_password"
        optional: true
      - environemnt_var: "POSTGRES_DB"
        var_type: "str"
        default: "postgres_db"
        optional: true

services:

  veld_jupyter:
    build: ./src/jupyter/
    command: jupyter notebook --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./src/jupyter/src/:/veld/code/
    working_dir: /veld/code/
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - veld_postgres

networks:
  veld_postgres:
    driver: bridge

